version: '3.8'

services:
  app:
    build: .
    ports:
      - "8130:8130"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    command: uvicorn app.main:app --host 0.0.0.0 --port 8130 --reload
