[project]
name = "sparse-embed-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "torch>=2.8.0",
    "transformers>=4.55.1",
    "uvicorn>=0.35.0",
]
